### PR TITLE
in-readtable does not touch swank:*readtable-alist* anymore

### PR DESCRIPTION
**Pull request by budden**
Hi! There was a discussion in a slime-devel mailing list: http://thread.gmane.org/gmane.lisp.slime.devel/11574

I'm about to create an appropriate pull request to SLIME.

### CODE REVIEW

**Comment by melisgl** [comment]
Skimming through that slime-devel thread, it's not clear there is a consensus on whether this is the right approach.

**Comment by budden** [comment]
> Skimming through that slime-devel thread, it's not clear there is a consensus on whether this is the right approach.

There is consensus about two things:
1. Understanding readtables in SLIME is useful and desired
2. Frobbing made by (in-readtable) is kludgy and potentially harmful.

But I'm not sure people understood that the change I suggest is breaking.

Currently, once readtable is associated to a package, every file with
that package implies that readtable due to record in
_readtable-alist_. So it is enough to issue (in-readtable) once in the
package and it sticks to that package until changed.

After suggested modification to SLIME and NAMED-READATBLES, explicit
in-readtable form is required at every file, and also every time we
issue in-package form in REPL.
We are also free to add records to _readtable-alist_ manually.

How will user adapt to suggested modifications? Simplest way is to
fill _readtable-alist_ in his initialization file.

**Comment by budden** [comment]
> After suggested modification to SLIME and NAMED-READATBLES, explicit
> in-readtable form is required at every file

in my understanding that has always been the published API/contract of
IN-READTABLE.

> and also every time we issue in-package form in REPL.

again, in my understanding IN-READTABLE and IN-PACKAGE were meant to
be independent. it's only a kludge that the implementation was
intertwined for a while, because proper implementation required slime
supporting IN-READTABLE similar to how it supports IN-PACKAGE. no one
got to implement it before you, so the _READTABLE-ALIST_ based kludge
made things work good enough for the time being.

i think catering for user code that relied on the sideffect of that
kludge is not a priority.

## 

• attila lendvai

## • PGP: 963F 5D5F 45C7 DFCD 0A39

“Those children who are beaten will in turn give beatings, those who
are intimidated will be intimidating, those who are humiliated will
impose humiliation, and those whose souls are murdered will murder.”
    — Alice Miller (1923–2010)

**Comment by attila-lendvai** [comment]
+1 for budden's solution.

at the same time i'm not overly happy about the idea of adding an in-readtable form to the top of every file when most of the time i prefer the same readtable for the entire package.

but then no one is forcing me to use named-readtables... but then i must be ready to accept the elevated complexity of e.g. hu.dwim.common that replaces cl:in-package with a custom macro to deal with the readtable setup, and thus requires a custom ASDF system class that deals with loading all this (and exposes bugs in ASDF and quicklisp being an early adopter of :defsystem-depends-on, etc, etc).

oh well.

**Comment by budden** [comment]
Hi! Sure my previous suggestion was not perfect, if we take the compatibility into account. This is the new one
https://bitbucket.org/budden/clcon/src/e3c40c555295336a3a13c506cce6a179f9dd8713/doc/how-to-support-readtable-with-slime.md?fileviewer=file-view-default - I'll post it to SLIME-devel also.

**Comment by melisgl** [comment]
I understand slime didn't take the patch so there isn't much to do here. Closing.

**Pull request closed without merging**
