### PR TITLE
Please merge CCL support.

### PR DESCRIPTION
**Pull request by fare**
Passes all tests again.

### CODE REVIEW

**Comment by fare** [comment]
This fixes issue #5

**Comment by melisgl** [comment]
Thanks for the patch. Sorry about the latency. I tested with the oldish 1.10-dev-r16128M-trunk version and it fails NAMED-READTABLES-TEST::DEFREADTABLE.2. Could backwards compatibility be perhaps maintained?

**Comment by fare** [comment]
Oops, I thought it was compatible, but failed to test with an old ccl.

I'll try again...

Sorry for the trouble.

**Comment by fare** [comment]
Well, I tried various old CCLs and my patch does work, without any failure in NAMED-READTABLES-TEST::DEFREADTABLE.2.

**Comment by melisgl** [comment]
Thanks. I pushed your changes. The CCL I tested signaled some unrelated condition that was picked up by the T type specifier in the test. I think that T is just a wee bit too wide.

**Pull request merged**
